# Generated by Django 4.0.4 on 2022-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italy', '0002_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
