# Generated by Django 4.0.4 on 2022-08-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('italy', '0007_meal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'catiegory', 'verbose_name_plural': 'catiegories'},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='active',
        ),
    ]
