# Generated by Django 4.0.4 on 2022-08-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italy', '0008_alter_category_options_remove_meal_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
