# Generated by Django 4.0.4 on 2022-08-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('italy', '0009_meal_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='active',
        ),
    ]
