# Generated by Django 4.0.4 on 2022-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italy', '0010_remove_meal_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, default='italy\\static\\images\\default.png', upload_to='images/'),
        ),
    ]
